name: Prepare project
description: setting all project and prepare all files

inputs:
  SECRET_TOKEN:
    description: token for private repository
    required: true

runs:
  using: "composite"
  steps:

      - name: Remove android about module old folder link
        run: |
              rm -rf aboutactivitymodel
              rm -rf ScheduleModule
              rm -rf ServicesModule
              rm -rf connect-gdrive
              rm -rf japl-android-graphs
              rm -rf ui
              rm -rf model
              rm -rf alameda181-core
        shell: bash

      - name: get Model
        uses: actions/checkout@v4
        with: 
         repository: ${{ github.actor }}/japl-android-homeconnect-model
         path: ./model

      - name: Get Core
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-homeconnect-core
          path: ./alameda181-core
          ref: alameda181

      - name: Get japl-android-about-module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-about-module
          path: ./aboutactivitymodule

      - name: Get japl-android-schedule-module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-schedule-module
          path: ./ScheduleModule

      - name: Get Service Module by Alameda 181
        uses: actions/checkout@v4
        with: 
         repository: ${{ github.actor }}/alameda181-android-services-module
         path: ./ServicesModule

      - name: Get japl-android-google-connect-module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-google-connect-module
          path: ./connect-gdrive

      - name: Get Finances to get Graphs module
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/Finances
          path: ./finances

      - name: Get japl-android-ui
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-android-ui
          path: ./ui

      - name: Get japl-properties
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/japl-properties
          ref: main
          path: ./japl-properties
          token: ${{ inputs.SECRET_TOKEN }}
      
      - name: Copy Values on project
        run: |
              ls ./japl-properties/alameda181/
              ls ./app
              cp ./japl-properties/alameda181/google_services.json ./app/google-services.json
              rm -rf ./connect-gdrive/src/main/res/raw
              mkdir ./connect-gdrive/src/main/res/raw
              cp ./japl-properties/alameda181/credentials.json ./connect-gdrive/src/main/res/raw/
              cp ./japl-properties/alameda181/cralameda181_34c486bb5b56.json ./connect-gdrive/src/main/res/raw/
              cp ./japl-properties/alameda181/uralameda181_keystorepassword.jks ./app/
              rm -rf ./japl-properties
        shell: bash

      - name: Duplication Folder on upper case UI
        run: ln -s ./ui ./UI
        shell: bash

      - name: link code to graphs folder
        run: ln -s ./finances/japl-android-graphs ./japl-android-graphs 
        shell: bash

      - name: Install Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: 17

      - name: Setup Graddle And Validations
        uses: gradle/actions/setup-gradle@v4
